lib:
let
  inherit (lib)
    concatStringsSep
    mapAttrsToList
    filterAttrs
    isList
    optional
    optionals
    boolToString
    ;

  needsQuote = k: builtins.match "[A-Za-z0-9_-]+" k == null;
  renderKey = k: if needsQuote k then ''"${k}"'' else k;

  str = s: ''"${lib.escape [ ''"'' "\\" ] s}"'';

  inputUrl =
    name: inp:
    if (inp.url or "") != "" then
      inp.url
    else
      let
        ref = if (inp.ref or "") != "" then "/${inp.ref}" else "";
      in
      if (inp.type or null) != null && (inp.owner or "") != "" then
        "${inp.type}:${inp.owner}/${inp.repo or ""}${ref}"
      else
        throw "tack serialize: input '${name}' has no url and cannot synthesise one";

  pinType =
    inp:
    if (inp.tackType or null) != null then
      inp.tackType
    else if (inp.flake or true) == false then
      "fetch"
    else
      null;

  followsTable =
    inp:
    let
      nested = inp.inputs or { };
      pairs = filterAttrs (_: v: (v.follows or null) != null) nested;
    in
    if pairs == { } then
      null
    else
      "{ "
      + concatStringsSep ", " (mapAttrsToList (c: v: "${renderKey c} = ${str v.follows}") pairs)
      + " }";

  renderInput =
    name: inp:
    concatStringsSep "\n" (
      [
        "[inputs.${renderKey name}]"
        "url = ${str (inputUrl name inp)}"
      ]
      ++ optional (pinType inp != null) "type = ${str (pinType inp)}"
      ++ optional ((inp.dir or "") != "") "dir = ${str inp.dir}"
      ++ optional ((inp.submodules or null) == true) "submodules = true"
      ++ optional ((inp.unpack or null) != null) "unpack = ${str inp.unpack}"
      ++ optional (followsTable inp != null) "follows = ${followsTable inp}"
    );

  renderShorturls =
    su:
    optionals (su != { }) ([ "[shorturls]" ] ++ mapAttrsToList (k: v: "${renderKey k} = ${str v}") su);

  renderAllFollow =
    af:
    optionals (af != { }) (
      [ "[all_follow]" ]
      ++ mapAttrsToList (
        k: v:
        if isList v then
          "${renderKey k} = [${concatStringsSep ", " (map str v)}]"
        else
          "${renderKey k} = ${str v}"
      ) af
    );

  renderTack =
    cfg:
    optionals ((cfg.recomposable or null) != null) [
      "[tack]"
      "recomposable = ${boolToString cfg.recomposable}"
    ];
in
cfg:
let
  header = concatStringsSep "\n" [
    "# tack pins. generated by flake-file write-tack."
    "# nix reads pins.lock.json; this file drives tack update"
  ];

  section = lines: optional (lines != [ ]) (concatStringsSep "\n" lines);

  blocks = [
    header
  ]
  ++ section (renderTack cfg)
  ++ section (renderShorturls (cfg.shorturls or { }))
  ++ section (renderAllFollow (cfg.allFollow or { }))
  ++ mapAttrsToList renderInput (cfg.inputs or { });
in
concatStringsSep "\n\n" blocks + "\n"
