{ lib, inputs, ... }:
let
  serialize = import "${inputs.flake-file}/modules/tack/serialize.nix" lib;

  header = "# tack pins. generated by flake-file write-tack.\n# nix reads pins.lock.json; this file drives tack update";

  tests.tackSerialize."test empty config renders header only" = {
    expr = serialize { };
    expected = header + "\n";
  };

  tests.tackSerialize."test recomposable table" = {
    expr = serialize { recomposable = true; };
    expected = header + "\n\n[tack]\nrecomposable = true\n";
  };

  tests.tackSerialize."test url passthrough" = {
    expr = serialize { inputs.foo.url = "github:a/b"; };
    expected = header + "\n\n[inputs.foo]\nurl = \"github:a/b\"\n";
  };

  tests.tackSerialize."test url synthesis from type owner repo ref" = {
    expr = serialize {
      inputs.foo = {
        type = "github";
        owner = "a";
        repo = "b";
        ref = "main";
      };
    };
    expected = header + "\n\n[inputs.foo]\nurl = \"github:a/b/main\"\n";
  };

  tests.tackSerialize."test missing url throws" = {
    expr =
      (builtins.tryEval (serialize {
        inputs.foo = { };
      })).success;
    expected = false;
  };

  tests.tackSerialize."test flake false becomes fetch pin" = {
    expr = serialize {
      inputs.foo = {
        url = "x";
        flake = false;
      };
    };
    expected = header + "\n\n[inputs.foo]\nurl = \"x\"\ntype = \"fetch\"\n";
  };

  tests.tackSerialize."test tackType wins over flake false" = {
    expr = serialize {
      inputs.foo = {
        url = "x";
        flake = false;
        tackType = "fixed";
      };
    };
    expected = header + "\n\n[inputs.foo]\nurl = \"x\"\ntype = \"fixed\"\n";
  };

  tests.tackSerialize."test fixed pin with unpack" = {
    expr = serialize {
      inputs.foo = {
        url = "x";
        tackType = "fixed";
        unpack = "tarball";
      };
    };
    expected = header + "\n\n[inputs.foo]\nurl = \"x\"\ntype = \"fixed\"\nunpack = \"tarball\"\n";
  };

  tests.tackSerialize."test follows table" = {
    expr = serialize {
      inputs.foo = {
        url = "x";
        inputs.nixpkgs.follows = "nixpkgs";
      };
    };
    expected = header + "\n\n[inputs.foo]\nurl = \"x\"\nfollows = { nixpkgs = \"nixpkgs\" }\n";
  };

  tests.tackSerialize."test dir and submodules" = {
    expr = serialize {
      inputs.foo = {
        url = "x";
        dir = "sub";
        submodules = true;
      };
    };
    expected = header + "\n\n[inputs.foo]\nurl = \"x\"\ndir = \"sub\"\nsubmodules = true\n";
  };

  tests.tackSerialize."test quoted input name" = {
    expr = serialize { inputs."dotted.name".url = "x"; };
    expected = header + "\n\n[inputs.\"dotted.name\"]\nurl = \"x\"\n";
  };

  tests.tackSerialize."test url escaping" = {
    expr = serialize { inputs.foo.url = "x\"y\\z"; };
    expected = header + "\n\n[inputs.foo]\nurl = \"x\\\"y\\\\z\"\n";
  };

  tests.tackSerialize."test shorturls" = {
    expr = serialize { shorturls.gh = "github:{path}"; };
    expected = header + "\n\n[shorturls]\ngh = \"github:{path}\"\n";
  };

  tests.tackSerialize."test all_follow string and list" = {
    expr = serialize {
      allFollow = {
        nixpkgs = [
          "nixpkgs-stable"
          "nixpkgs-unstable"
        ];
        systems = "systems";
      };
    };
    expected =
      header
      + "\n\n[all_follow]\nnixpkgs = [\"nixpkgs-stable\", \"nixpkgs-unstable\"]\nsystems = \"systems\"\n";
  };

  tests.tackSerialize."test inputs sorted by name" = {
    expr = serialize {
      inputs.zeta.url = "z";
      inputs.alpha.url = "a";
    };
    expected = header + "\n\n[inputs.alpha]\nurl = \"a\"\n\n[inputs.zeta]\nurl = \"z\"\n";
  };
in
{
  flake = { inherit tests; };
}
