{
  pkgs ? import <nixpkgs> { },
  modules ? [ ],
  bootstrap ? [ ],
  outdir ? ".",
  inputs ? null,
  outputs ? null,
  do-not-edit ? null,
  import-tree ? (
    pkgs.fetchFromGitHub {
      owner = "vic";
      repo = "import-tree";
      rev = "c968d3b54d12cf5d9c13f16f7c545a06c9d1fde6";
      hash = "sha256-oYO4poyw0Sb/db2PigqugMlDwsvwLg6CSpFrMUWxA3Q=";
    }
  ),
  ...
}:
let
  inherit (pkgs) lib;

  tree = (import import-tree) modules;

  bootstrapModule =
    if bootstrap == true then
      ./inputs.nix
    else if builtins.isList bootstrap then
      let
        allInputs = (import ./inputs.nix { inherit lib; }).flake-file.inputs;
      in
      { flake-file.inputs = lib.filterAttrs (name: _: builtins.elem name bootstrap) allInputs; }
    else if bootstrap == false then
      { }
    else
      throw "flake-file bootstrap must be true, false, or a list of input names";

  attrsOpt = lib.mkOption {
    default = { };
    type = lib.types.submodule { freeformType = lib.types.lazyAttrsOf lib.types.unspecified; };
  };

  module = {
    imports = [
      bootstrapModule
      tree
      ./../default.nix
      ./../options
      ./../npins
      ./../unflake
      ./../tack
      ./../write-inputs.nix
      ./../write-flake.nix
      ./../write-lock.nix
      ./../flake-options.nix
      (lib.optionalAttrs (inputs != null) { flake-file.inputs = inputs; })
      (lib.optionalAttrs (outputs != null) { flake-file.outputs = strOrFile outputs; })
      (lib.optionalAttrs (do-not-edit != null) { flake-file.do-not-edit = strOrFile do-not-edit; })

      bootstrap-app
    ];
    config.flake-file.intoPath = outdir;
    options = {
      lib = attrsOpt;
      templates = attrsOpt;
      flakeModules = attrsOpt;
    };
  };

  strOrFile = str: if builtins.isPath str then builtins.readFile str else str;

  bootstrap-app = {
    flake-file.apps.bootstrap =
      pkgs:
      let
        inputs = ''{ flake-file.url = "github:vic/flake-file"; }'';
        notice = pkgs.writeText "notice" ''
          # DO-NOT-EDIT. Generated by github:vic/flake-file from flake-file.nix. Regen with:
          # nix-shell https://github.com/vic/flake-file/archive/main.zip -A bootstrap --run bootstrap
        '';
      in
      pkgs.writeShellApplication {
        name = "bootstrap";
        text = ''
          if ! test -f flake-file.nix; then
            cp flake.nix flake-file.nix
          fi
          nix-shell ${../..} -A write-flake --run write-flake \
            --arg modules ./flake-file.nix \
            --arg do-not-edit ${notice} \
            --argstr outputs flake-module \
            --arg inputs '${inputs}'
        '';
      };
  };

  evaled = lib.evalModules { modules = [ module ]; };

  appPackages = lib.mapAttrs (
    _: app: pkgs.mkShell { buildInputs = [ (app pkgs) ]; }
  ) evaled.config.flake-file.apps;

in
evaled.config // appPackages
